#ConfgUsuario
#Sat Jun 07 17:33:07 ART 2025
acelerarJuego=5
autodestruccion=6
bEfectoSonido=Q
bMusica=W
efectoSonidoBox=true
habilidad1=1
habilidad2=2
habilidad3=3
habilidad4=4
musicaBox=true
pantallaCompleta=false
pausar=P
pistaMusical=Original
skin=Original
ventana=true
